# Generated by Django 3.0.7 on 2020-07-09 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='employees',
        ),
    ]
