# Generated by Django 3.0.7 on 2020-07-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20200709_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.TextField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
