# Generated by Django 3.0.7 on 2020-07-21 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20200709_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='csvDb',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data', models.TextField()),
            ],
        ),
    ]
