# Generated by Django 3.0.7 on 2020-07-21 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_csvdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csvdb',
            old_name='Data',
            new_name='DataBase',
        ),
    ]
